name: Unity Demo CI

on: [push]

env:
  version: 0.3

jobs:
  build:
    name: Build using Unity 🦄
    runs-on: windows-latest
      
    steps:
      # See https://github.com/marketplace/actions/unity-builder
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1.2
        with:
          unityVersion: 2019.3.0f6
