name: Unity Demo CI

on: [push]

jobs:
  build:
    name: Build using Unity 🦄
    runs-on: windows-latest
      
    steps:
      # See https://github.com/marketplace/actions/unity-builder
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install and Activate Unity
        run: |
          Install-Module UnitySetup -Force
          Import-Module UnitySetup
          Find-UnitySetupInstaller -Version $env:UNITY_VERSION -Components 'Windows','UWP' | Install-UnitySetupInstance -Verbose
        shell: pwsh
        env:
          UNITY_VERSION: 2019.3.0f6
          
      - name: Activate Unity
        run: |
          "C:\Program Files\Unity\Editor\Unity.exe" -batchmode -quit -verbose -wait -nographics -username $env:UNITY_EMAIL -password $env:PASSWORD -serial $env:UNITY_SERIAL
        shell: cmd
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      - name: Build Unity Project
        run: |
          "C:\Program Files\Unity\Editor\Unity.exe" -batchmode -quit -verbose -wait -nographics -projectPath "Unity-Demo/" -executeMethod Microsoft.MixedReality.Toolkit.Build.Editor.UnityPlayerBuildTools.StartCommandLineBuild
        shell: cmd
