name: Unity Demo CI

on: [push]

jobs:
  build:
    name: Build using Unity 🦄
    runs-on: ubuntu-latest
    container:
      image: gableroux/unity3d:2019.3.1f1-windows-update-2020-02-17
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      
    steps:
      # See https://github.com/marketplace/actions/unity-builder
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v2
