name: Unity Demo CI

on: [push]

jobs:
  build:
    name: Build using Unity 🦄
    runs-on: ubuntu-latest
    container:
      image: jwendl/unity-windows-uwp:latest
      
    steps:
      # See https://github.com/marketplace/actions/unity-builder
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Activate Unity
        run: powershell Start-UnityEditor -BatchMode -Quit -Verbose -Wait -AdditionalArguments "-nographics -username $env:UNITY_EMAIL -password $env:PASSWORD -serial $env:UNITY_SERIAL"
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
